// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traceinfo.proto

package com.yahoo.ycsb.db;

public final class Traceinfo {
  private Traceinfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TraceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TraceInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string req_type = 1;</code>
     */
    java.lang.String getReqType();
    /**
     * <code>optional string req_type = 1;</code>
     */
    com.google.protobuf.ByteString
        getReqTypeBytes();

    /**
     * <code>optional bytes coordinator_addr = 2;</code>
     */
    com.google.protobuf.ByteString getCoordinatorAddr();

    /**
     * <code>optional int32 duration_micros = 3;</code>
     */
    int getDurationMicros();

    /**
     * <code>repeated .Event events = 4;</code>
     */
    java.util.List<com.yahoo.ycsb.db.Traceinfo.Event> 
        getEventsList();
    /**
     * <code>repeated .Event events = 4;</code>
     */
    com.yahoo.ycsb.db.Traceinfo.Event getEvents(int index);
    /**
     * <code>repeated .Event events = 4;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated .Event events = 4;</code>
     */
    java.util.List<? extends com.yahoo.ycsb.db.Traceinfo.EventOrBuilder> 
        getEventsOrBuilderList();
    /**
     * <code>repeated .Event events = 4;</code>
     */
    com.yahoo.ycsb.db.Traceinfo.EventOrBuilder getEventsOrBuilder(
        int index);

    /**
     * <code>optional int64 req_end_time_millis = 5;</code>
     */
    long getReqEndTimeMillis();
  }
  /**
   * Protobuf type {@code TraceInfo}
   */
  public  static final class TraceInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TraceInfo)
      TraceInfoOrBuilder {
    // Use TraceInfo.newBuilder() to construct.
    private TraceInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TraceInfo() {
      reqType_ = "";
      coordinatorAddr_ = com.google.protobuf.ByteString.EMPTY;
      durationMicros_ = 0;
      events_ = java.util.Collections.emptyList();
      reqEndTimeMillis_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TraceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              reqType_ = s;
              break;
            }
            case 18: {

              coordinatorAddr_ = input.readBytes();
              break;
            }
            case 24: {

              durationMicros_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                events_ = new java.util.ArrayList<com.yahoo.ycsb.db.Traceinfo.Event>();
                mutable_bitField0_ |= 0x00000008;
              }
              events_.add(input.readMessage(com.yahoo.ycsb.db.Traceinfo.Event.parser(), extensionRegistry));
              break;
            }
            case 40: {

              reqEndTimeMillis_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.ycsb.db.Traceinfo.internal_static_TraceInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.ycsb.db.Traceinfo.internal_static_TraceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.ycsb.db.Traceinfo.TraceInfo.class, com.yahoo.ycsb.db.Traceinfo.TraceInfo.Builder.class);
    }

    private int bitField0_;
    public static final int REQ_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object reqType_;
    /**
     * <code>optional string req_type = 1;</code>
     */
    public java.lang.String getReqType() {
      java.lang.Object ref = reqType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string req_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqTypeBytes() {
      java.lang.Object ref = reqType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COORDINATOR_ADDR_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString coordinatorAddr_;
    /**
     * <code>optional bytes coordinator_addr = 2;</code>
     */
    public com.google.protobuf.ByteString getCoordinatorAddr() {
      return coordinatorAddr_;
    }

    public static final int DURATION_MICROS_FIELD_NUMBER = 3;
    private int durationMicros_;
    /**
     * <code>optional int32 duration_micros = 3;</code>
     */
    public int getDurationMicros() {
      return durationMicros_;
    }

    public static final int EVENTS_FIELD_NUMBER = 4;
    private java.util.List<com.yahoo.ycsb.db.Traceinfo.Event> events_;
    /**
     * <code>repeated .Event events = 4;</code>
     */
    public java.util.List<com.yahoo.ycsb.db.Traceinfo.Event> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .Event events = 4;</code>
     */
    public java.util.List<? extends com.yahoo.ycsb.db.Traceinfo.EventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .Event events = 4;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .Event events = 4;</code>
     */
    public com.yahoo.ycsb.db.Traceinfo.Event getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .Event events = 4;</code>
     */
    public com.yahoo.ycsb.db.Traceinfo.EventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }

    public static final int REQ_END_TIME_MILLIS_FIELD_NUMBER = 5;
    private long reqEndTimeMillis_;
    /**
     * <code>optional int64 req_end_time_millis = 5;</code>
     */
    public long getReqEndTimeMillis() {
      return reqEndTimeMillis_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReqTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, reqType_);
      }
      if (!coordinatorAddr_.isEmpty()) {
        output.writeBytes(2, coordinatorAddr_);
      }
      if (durationMicros_ != 0) {
        output.writeInt32(3, durationMicros_);
      }
      for (int i = 0; i < events_.size(); i++) {
        output.writeMessage(4, events_.get(i));
      }
      if (reqEndTimeMillis_ != 0L) {
        output.writeInt64(5, reqEndTimeMillis_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReqTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, reqType_);
      }
      if (!coordinatorAddr_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, coordinatorAddr_);
      }
      if (durationMicros_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, durationMicros_);
      }
      for (int i = 0; i < events_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, events_.get(i));
      }
      if (reqEndTimeMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, reqEndTimeMillis_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yahoo.ycsb.db.Traceinfo.TraceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TraceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TraceInfo)
        com.yahoo.ycsb.db.Traceinfo.TraceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.ycsb.db.Traceinfo.internal_static_TraceInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.ycsb.db.Traceinfo.internal_static_TraceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.ycsb.db.Traceinfo.TraceInfo.class, com.yahoo.ycsb.db.Traceinfo.TraceInfo.Builder.class);
      }

      // Construct using com.yahoo.ycsb.db.Traceinfo.TraceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        reqType_ = "";

        coordinatorAddr_ = com.google.protobuf.ByteString.EMPTY;

        durationMicros_ = 0;

        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          eventsBuilder_.clear();
        }
        reqEndTimeMillis_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.ycsb.db.Traceinfo.internal_static_TraceInfo_descriptor;
      }

      public com.yahoo.ycsb.db.Traceinfo.TraceInfo getDefaultInstanceForType() {
        return com.yahoo.ycsb.db.Traceinfo.TraceInfo.getDefaultInstance();
      }

      public com.yahoo.ycsb.db.Traceinfo.TraceInfo build() {
        com.yahoo.ycsb.db.Traceinfo.TraceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.ycsb.db.Traceinfo.TraceInfo buildPartial() {
        com.yahoo.ycsb.db.Traceinfo.TraceInfo result = new com.yahoo.ycsb.db.Traceinfo.TraceInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.reqType_ = reqType_;
        result.coordinatorAddr_ = coordinatorAddr_;
        result.durationMicros_ = durationMicros_;
        if (eventsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            events_ = java.util.Collections.unmodifiableList(events_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.events_ = events_;
        } else {
          result.events_ = eventsBuilder_.build();
        }
        result.reqEndTimeMillis_ = reqEndTimeMillis_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.ycsb.db.Traceinfo.TraceInfo) {
          return mergeFrom((com.yahoo.ycsb.db.Traceinfo.TraceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.ycsb.db.Traceinfo.TraceInfo other) {
        if (other == com.yahoo.ycsb.db.Traceinfo.TraceInfo.getDefaultInstance()) return this;
        if (!other.getReqType().isEmpty()) {
          reqType_ = other.reqType_;
          onChanged();
        }
        if (other.getCoordinatorAddr() != com.google.protobuf.ByteString.EMPTY) {
          setCoordinatorAddr(other.getCoordinatorAddr());
        }
        if (other.getDurationMicros() != 0) {
          setDurationMicros(other.getDurationMicros());
        }
        if (eventsBuilder_ == null) {
          if (!other.events_.isEmpty()) {
            if (events_.isEmpty()) {
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureEventsIsMutable();
              events_.addAll(other.events_);
            }
            onChanged();
          }
        } else {
          if (!other.events_.isEmpty()) {
            if (eventsBuilder_.isEmpty()) {
              eventsBuilder_.dispose();
              eventsBuilder_ = null;
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000008);
              eventsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEventsFieldBuilder() : null;
            } else {
              eventsBuilder_.addAllMessages(other.events_);
            }
          }
        }
        if (other.getReqEndTimeMillis() != 0L) {
          setReqEndTimeMillis(other.getReqEndTimeMillis());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.ycsb.db.Traceinfo.TraceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.ycsb.db.Traceinfo.TraceInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object reqType_ = "";
      /**
       * <code>optional string req_type = 1;</code>
       */
      public java.lang.String getReqType() {
        java.lang.Object ref = reqType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string req_type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReqTypeBytes() {
        java.lang.Object ref = reqType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string req_type = 1;</code>
       */
      public Builder setReqType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string req_type = 1;</code>
       */
      public Builder clearReqType() {
        
        reqType_ = getDefaultInstance().getReqType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string req_type = 1;</code>
       */
      public Builder setReqTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString coordinatorAddr_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes coordinator_addr = 2;</code>
       */
      public com.google.protobuf.ByteString getCoordinatorAddr() {
        return coordinatorAddr_;
      }
      /**
       * <code>optional bytes coordinator_addr = 2;</code>
       */
      public Builder setCoordinatorAddr(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        coordinatorAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes coordinator_addr = 2;</code>
       */
      public Builder clearCoordinatorAddr() {
        
        coordinatorAddr_ = getDefaultInstance().getCoordinatorAddr();
        onChanged();
        return this;
      }

      private int durationMicros_ ;
      /**
       * <code>optional int32 duration_micros = 3;</code>
       */
      public int getDurationMicros() {
        return durationMicros_;
      }
      /**
       * <code>optional int32 duration_micros = 3;</code>
       */
      public Builder setDurationMicros(int value) {
        
        durationMicros_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 duration_micros = 3;</code>
       */
      public Builder clearDurationMicros() {
        
        durationMicros_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.yahoo.ycsb.db.Traceinfo.Event> events_ =
        java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          events_ = new java.util.ArrayList<com.yahoo.ycsb.db.Traceinfo.Event>(events_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.yahoo.ycsb.db.Traceinfo.Event, com.yahoo.ycsb.db.Traceinfo.Event.Builder, com.yahoo.ycsb.db.Traceinfo.EventOrBuilder> eventsBuilder_;

      /**
       * <code>repeated .Event events = 4;</code>
       */
      public java.util.List<com.yahoo.ycsb.db.Traceinfo.Event> getEventsList() {
        if (eventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(events_);
        } else {
          return eventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public int getEventsCount() {
        if (eventsBuilder_ == null) {
          return events_.size();
        } else {
          return eventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public com.yahoo.ycsb.db.Traceinfo.Event getEvents(int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);
        } else {
          return eventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public Builder setEvents(
          int index, com.yahoo.ycsb.db.Traceinfo.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.set(index, value);
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public Builder setEvents(
          int index, com.yahoo.ycsb.db.Traceinfo.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public Builder addEvents(com.yahoo.ycsb.db.Traceinfo.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public Builder addEvents(
          int index, com.yahoo.ycsb.db.Traceinfo.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(index, value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public Builder addEvents(
          com.yahoo.ycsb.db.Traceinfo.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public Builder addEvents(
          int index, com.yahoo.ycsb.db.Traceinfo.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends com.yahoo.ycsb.db.Traceinfo.Event> values) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, events_);
          onChanged();
        } else {
          eventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public Builder clearEvents() {
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public Builder removeEvents(int index) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.remove(index);
          onChanged();
        } else {
          eventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public com.yahoo.ycsb.db.Traceinfo.Event.Builder getEventsBuilder(
          int index) {
        return getEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public com.yahoo.ycsb.db.Traceinfo.EventOrBuilder getEventsOrBuilder(
          int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);  } else {
          return eventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public java.util.List<? extends com.yahoo.ycsb.db.Traceinfo.EventOrBuilder> 
           getEventsOrBuilderList() {
        if (eventsBuilder_ != null) {
          return eventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(events_);
        }
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public com.yahoo.ycsb.db.Traceinfo.Event.Builder addEventsBuilder() {
        return getEventsFieldBuilder().addBuilder(
            com.yahoo.ycsb.db.Traceinfo.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public com.yahoo.ycsb.db.Traceinfo.Event.Builder addEventsBuilder(
          int index) {
        return getEventsFieldBuilder().addBuilder(
            index, com.yahoo.ycsb.db.Traceinfo.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .Event events = 4;</code>
       */
      public java.util.List<com.yahoo.ycsb.db.Traceinfo.Event.Builder> 
           getEventsBuilderList() {
        return getEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.yahoo.ycsb.db.Traceinfo.Event, com.yahoo.ycsb.db.Traceinfo.Event.Builder, com.yahoo.ycsb.db.Traceinfo.EventOrBuilder> 
          getEventsFieldBuilder() {
        if (eventsBuilder_ == null) {
          eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.yahoo.ycsb.db.Traceinfo.Event, com.yahoo.ycsb.db.Traceinfo.Event.Builder, com.yahoo.ycsb.db.Traceinfo.EventOrBuilder>(
                  events_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        return eventsBuilder_;
      }

      private long reqEndTimeMillis_ ;
      /**
       * <code>optional int64 req_end_time_millis = 5;</code>
       */
      public long getReqEndTimeMillis() {
        return reqEndTimeMillis_;
      }
      /**
       * <code>optional int64 req_end_time_millis = 5;</code>
       */
      public Builder setReqEndTimeMillis(long value) {
        
        reqEndTimeMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 req_end_time_millis = 5;</code>
       */
      public Builder clearReqEndTimeMillis() {
        
        reqEndTimeMillis_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TraceInfo)
    }

    // @@protoc_insertion_point(class_scope:TraceInfo)
    private static final com.yahoo.ycsb.db.Traceinfo.TraceInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yahoo.ycsb.db.Traceinfo.TraceInfo();
    }

    public static com.yahoo.ycsb.db.Traceinfo.TraceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TraceInfo>
        PARSER = new com.google.protobuf.AbstractParser<TraceInfo>() {
      public TraceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TraceInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TraceInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TraceInfo> getParserForType() {
      return PARSER;
    }

    public com.yahoo.ycsb.db.Traceinfo.TraceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes source = 1;</code>
     */
    com.google.protobuf.ByteString getSource();

    /**
     * <code>optional string desc = 2;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>optional int32 duration_micros = 3;</code>
     */
    int getDurationMicros();
  }
  /**
   * Protobuf type {@code Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Event)
      EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Event() {
      source_ = com.google.protobuf.ByteString.EMPTY;
      desc_ = "";
      durationMicros_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              source_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 24: {

              durationMicros_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.ycsb.db.Traceinfo.internal_static_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.ycsb.db.Traceinfo.internal_static_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.ycsb.db.Traceinfo.Event.class, com.yahoo.ycsb.db.Traceinfo.Event.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString source_;
    /**
     * <code>optional bytes source = 1;</code>
     */
    public com.google.protobuf.ByteString getSource() {
      return source_;
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private volatile java.lang.Object desc_;
    /**
     * <code>optional string desc = 2;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>optional string desc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURATION_MICROS_FIELD_NUMBER = 3;
    private int durationMicros_;
    /**
     * <code>optional int32 duration_micros = 3;</code>
     */
    public int getDurationMicros() {
      return durationMicros_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!source_.isEmpty()) {
        output.writeBytes(1, source_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, desc_);
      }
      if (durationMicros_ != 0) {
        output.writeInt32(3, durationMicros_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!source_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, source_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, desc_);
      }
      if (durationMicros_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, durationMicros_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.yahoo.ycsb.db.Traceinfo.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Traceinfo.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Traceinfo.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Traceinfo.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Traceinfo.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Traceinfo.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Traceinfo.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Traceinfo.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Traceinfo.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Traceinfo.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yahoo.ycsb.db.Traceinfo.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Event)
        com.yahoo.ycsb.db.Traceinfo.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.ycsb.db.Traceinfo.internal_static_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.ycsb.db.Traceinfo.internal_static_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.ycsb.db.Traceinfo.Event.class, com.yahoo.ycsb.db.Traceinfo.Event.Builder.class);
      }

      // Construct using com.yahoo.ycsb.db.Traceinfo.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        source_ = com.google.protobuf.ByteString.EMPTY;

        desc_ = "";

        durationMicros_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.ycsb.db.Traceinfo.internal_static_Event_descriptor;
      }

      public com.yahoo.ycsb.db.Traceinfo.Event getDefaultInstanceForType() {
        return com.yahoo.ycsb.db.Traceinfo.Event.getDefaultInstance();
      }

      public com.yahoo.ycsb.db.Traceinfo.Event build() {
        com.yahoo.ycsb.db.Traceinfo.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.ycsb.db.Traceinfo.Event buildPartial() {
        com.yahoo.ycsb.db.Traceinfo.Event result = new com.yahoo.ycsb.db.Traceinfo.Event(this);
        result.source_ = source_;
        result.desc_ = desc_;
        result.durationMicros_ = durationMicros_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.ycsb.db.Traceinfo.Event) {
          return mergeFrom((com.yahoo.ycsb.db.Traceinfo.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.ycsb.db.Traceinfo.Event other) {
        if (other == com.yahoo.ycsb.db.Traceinfo.Event.getDefaultInstance()) return this;
        if (other.getSource() != com.google.protobuf.ByteString.EMPTY) {
          setSource(other.getSource());
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (other.getDurationMicros() != 0) {
          setDurationMicros(other.getDurationMicros());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.ycsb.db.Traceinfo.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.ycsb.db.Traceinfo.Event) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString source_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes source = 1;</code>
       */
      public com.google.protobuf.ByteString getSource() {
        return source_;
      }
      /**
       * <code>optional bytes source = 1;</code>
       */
      public Builder setSource(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes source = 1;</code>
       */
      public Builder clearSource() {
        
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 2;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 2;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 2;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 2;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private int durationMicros_ ;
      /**
       * <code>optional int32 duration_micros = 3;</code>
       */
      public int getDurationMicros() {
        return durationMicros_;
      }
      /**
       * <code>optional int32 duration_micros = 3;</code>
       */
      public Builder setDurationMicros(int value) {
        
        durationMicros_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 duration_micros = 3;</code>
       */
      public Builder clearDurationMicros() {
        
        durationMicros_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Event)
    }

    // @@protoc_insertion_point(class_scope:Event)
    private static final com.yahoo.ycsb.db.Traceinfo.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yahoo.ycsb.db.Traceinfo.Event();
    }

    public static com.yahoo.ycsb.db.Traceinfo.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Event(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    public com.yahoo.ycsb.db.Traceinfo.Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TraceInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TraceInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017traceinfo.proto\"\205\001\n\tTraceInfo\022\020\n\010req_t" +
      "ype\030\001 \001(\t\022\030\n\020coordinator_addr\030\002 \001(\014\022\027\n\017d" +
      "uration_micros\030\003 \001(\005\022\026\n\006events\030\004 \003(\0132\006.E" +
      "vent\022\033\n\023req_end_time_millis\030\005 \001(\003\">\n\005Eve" +
      "nt\022\016\n\006source\030\001 \001(\014\022\014\n\004desc\030\002 \001(\t\022\027\n\017dura" +
      "tion_micros\030\003 \001(\005B\023\n\021com.yahoo.ycsb.dbb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TraceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TraceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TraceInfo_descriptor,
        new java.lang.String[] { "ReqType", "CoordinatorAddr", "DurationMicros", "Events", "ReqEndTimeMillis", });
    internal_static_Event_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Event_descriptor,
        new java.lang.String[] { "Source", "Desc", "DurationMicros", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
